<div class="body-content">
	<h1>Antecedentes</h1>

	<div class="content">
		<p>El Instituto Politécnico Tomás Katari - IPTK fue fundado el 02 de septiembre de 1976, en el pueblo de Ocurí, Provincia Chayanta del Departamento de Potosí, por el Dr. Franz Barrios Villegas. Nació en un momento en que el país enfrentaba un periodo de dictadura. Su propósito de creación fue enfrentar cuatro problemas críticos y estructurales de la Provincia:</p>
		<ul>
			<li>Mortalidad.</li>
			<li>Extrema pobreza.</li>
			<li>Explotación en el trabajo de los mineros.</li>
			<li>Corrupción en las autoridades locales.</li>
		</ul>
		<p>Para lograr su meta, estructuró cuatro departamentos y una acción integral de investigación aplicada, asistencia técnica, organización de las bases y educación, cumpliendo así las tareas de un Estado ausente en la zona. En los años 80 expandió sus acciones a la ciudad de Sucre para asentar sus oficinas centrales, y prestar servicio a los migrantes de la Provincia Chayanta y las familias en situación de sobreexplotación y pobreza de los barrios marginales de la ciudad. Esta, es la década de la implementación de una economía de libre mercado en el país, relocalización de mineros y un fuerte movimiento migracional de campesinos y mineros a las ciudades. Tanto en Chayanta como en Sucre, descentraliza su trabajo formando los Centros Integrales Multiactivos (CIMA’s), donde se planifican y ejecutan acciones integrales en áreas geográficas y población definidas, contando cada CIMA con oficinas, logística y personal multidisciplinario. Hasta el momento Bolivia ha vivido una serie de reformas estructurales del Estado, entre ellas la Participación Popular, que se dan a partir de 1994, marcan una nueva etapa institucional, en la que se impulsa la institucionalización del poder local municipal, la plena participación social-política-ciudadana de los nuevos actores locales, y una concepción de desarrollo más integral y sostenible. El surgimiento y empoderamiento significativo de los movimientos sociales y la explosión social del 2003 marca un nuevo hito para el Estado, con una nueva estructura de gobierno. Este cambio histórico y estructural que vive hoy Bolivia – como fruto de la eclosión social de octubre del año 2003 y el cambio político de diciembre de 2005 – representa para el IPTK, la culminación efectiva de todo lo que anheló para el país desde hace 34 años. Esta constatación le impone la readecuación de sus principales fundamentos y le abre la posibilidad de seguir participando activamente en la transformación que requiere el país. Inmersos en este proceso de cambio hemos decidió contribuir con toda nuestra experiencia y fortaleza institucional en aquellos ámbitos y espacios que se muestran como un flanco débil para el propio Estado. Para ello está privilegiando, mediante una línea precisa de programas y proyectos, su competencia institucional principalmente en los ámbitos de: Desarrollo del Conocimiento; Desarrollo Humano y Desarrollo Económico productivo con enfoque en seguridad alimentaria.</p>
	</div>
</div>
